- docs/faq.md
For dockstore/dockstore#1952
Removed the Avro warning as I do not believe it's an issue anymore. Update the doc to make Python 3 the default.
> Update for Python 3

- docs/index.rst
https://github.com/dockstore/dockstore/issues/2901
The landing page of the docs now includes a high level listing of each section and the names of each page.
> added toc to the landing page

- docs/getting-started/getting-started-with-cwl.rst
- docs/getting-started/getting-started-with-nextflow.rst
- docs/getting-started/getting-started-with-wdl.rst
https://github.com/dockstore/dockstore/issues/3115
README is now used as a fallback if no description is given in the primary descriptor.
> mentioned readme as a fallback to description

- docs/_static/language-support.html
Add Google Cloud Storage to the list of storage systems supported in file provisioning 
Addresses https://ucsc-cgl.atlassian.net/browse/DOCK-1132
> Add GCS support

- docs/_static/language-support.html
- docs/advanced-topics/advanced-features.rst
- docs/advanced-topics/developing-file-provisioning-plugins.rst
- docs/dockstore-introduction.rst
- docs/end-user-topics/language-support.rst
- docs/faq.rst
- docs/getting-started/getting-started-with-wdl.rst
- docs/index.rst
- docs/launch-with/launch.rst
- docs/news/2017-05-05-Upcoming-Features.rst
File provisioning out is supported for Cromwell WDL if you use the Dockstore CLI optional parameter –wdl-output-target which allows you to specify a remote path to provision output files to ex: s3://oicr.temp/testing-launcher/
> Add docs support for WDL output file provisioning

- docs/advanced-topics/checksum-support.rst
Documentation for checksum validation implemented [here](https://github.com/dockstore/dockstore-cli/pull/45).
> CLI checksum validation documentation 

- docs/advanced-topics/checksum-support.rst
Reverts dockstore/dockstore-documentation#81
Changes not yet released for CLI, moving to 1.10 branch
> Revert "CLI checksum validation documentation "

- docs/advanced-topics/advanced-features.rst
- docs/advanced-topics/aws-batch.rst
- docs/advanced-topics/azure-batch.rst
- docs/advanced-topics/batch-services.rst
- docs/advanced-topics/checker-workflow-trs.rst
- docs/advanced-topics/checker-workflows.rst
- docs/advanced-topics/conversions.rst
- docs/advanced-topics/posting-zips.rst
- docs/advanced-topics/set-up-file-provisioning-plugins.rst
- docs/dockstore-introduction.rst
- docs/end-user-topics/end-user-topics.rst
- docs/end-user-topics/language-support.rst
- docs/faq.rst
- docs/getting-started/getting-started.rst
- docs/getting-started/register-on-dockstore.rst
- docs/launch-with/anvil-launch-with.rst
- docs/launch-with/cgc-launch-with.rst
- docs/launch-with/dnastack-launch-with.rst
- docs/launch-with/launch.rst
- docs/launch-with/terra-launch-with.rst
- docs/news/2017-05-05-Upcoming-Features.rst
- docs/news/2018-04-05-Dockstore-1.4.0.rst
- docs/news/2018-09-12-Dockstore-1.5.0.rst
- docs/news/2019-04-08-Dockstore-1.6.0.rst
- docs/news/2019-09-26-Dockstore-1.7.0.rst
Ticket: https://ucsc-cgl.atlassian.net/browse/DOCK-1621
Links can be represented with different roles, [sphinx docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html), the command `make linkcheck` specifically expects external links, which is why all our local links were flagged as broken. Here are some approaches that can be used for links:
1. external links:
<code>\`text \<url\>\`</code>
2. link to a local document:
<code>:doc:\`text \</path/to/rst/file\>\`</code>
3. link to specific place in a local document:
3a. Create a label in the document you want to link to with the following: <code>.. _<b>label-name</b>:</code> ( _ before label name is required)
3b. link to the label with: <code>:ref:\`text \<label-name\>\`</code>
> Fixed local links so that linkcheck no longer throws a errors

- docs/advanced-topics/checker-workflows.rst
For dockstore/dockstore#3973
Most of the documentation is the same for WDL and CWL (and will be for other languages). Instead of duplicating the documentation, I just made a table with file equivalents.
> Add table for WDL equivalent

- docs/assets/templates/.dockstore.yml
- docs/getting-started/github-apps/github-apps.rst
Main ticket: https://github.com/dockstore/dockstore/issues/4100
Relevant feature PR: https://github.com/dockstore/dockstore/pull/4085
Adding documentation for setting workflow/service publish state via `.dockstore.yml`.
> add .dockstore.yml publish documentation

- docs/news/2020-12-03-Dockstore-1.10.0.rst
This was taken from GitHub with the modifications I made the other day and converted to reStructured Text.
I've reviewed it readthedocs.org.
> SEAB-2745 - Add 1.10.0 release notes to docs.dockstore.org

- docs/advanced-topics/checksum-support.rst
- docs/conf.py
We added notes on checking the presence of checksums but not verifying them. This improves the status of that slightly and mentions the CLI feature verifying descriptor checksums.
https://ucsc-cgl.atlassian.net/browse/SEAB-1510
> Add help on checksum verification

- docs/news/2021-07-14-Dockstore-1.11.5.rst
Added a file that now references the 1.11.5 version description on GitHub for the 1.11 release notes.
This is a change in that previously docs.docstore.org hosted its own copy of the release notes.
This does not contain the style_external_links change since that depends on the logo work which is still in the 'develop' branch.
> Add link to 1.11 Release Notes on GitHub

- docs/getting-started/getting-started-with-wdl.rst
Pretty much any substantial scattered workflow will cause issues if this is not set.
The information is adapted from [this document](https://github.com/DataBiosphere/analysis_pipeline_WDL/blob/main/_documentation_/for%20users/running-locally.md), which probably doesn't belong in the UWGAC repo.
It can be argued this should get its own page as it relates to setting up a Cromwell configuration file, which could be useful for stuff besides the concurrent job limit, and so we can point users to it out of context of a tutorial... but for now this seems like a good place for this information.
> Add information on setting Cromwell's concurrent-job-limit for local testing

- docs/conf.py
Enable the setting that displays an external link indicator at the end of any links in the documentation that leave docs.dockstore.org.
This is a config file setting that, at the end of eternal links ![display a box with an arrow pointing from the lower-left corner and passing through the upper right corner](https://user-images.githubusercontent.com/15311001/132060268-c2f4d977-8192-4ea9-8646-3ac3bd5db4c7.png).  
It does not display on external links in the Table of Contents section of the documentation.  I have been unable to find an option for that instance.
> Enable html_theme_options:style_external_links

- docs/docker_instructions.md
This fixes the warnings we've been getting during `make html`. This works with both our existing version of recommonmark and with #155. In other words this is not dependent on, but it is compatible with, #155.
This should be merged *before* #153.
> Fix markdown file's headers

- docs/conf.py
- docs/requirements.txt
- requirements.txt
recommonmark is deprecated: https://github.com/readthedocs/recommonmark/issues/221
This is not an essential fix, just something I noticed while researching other errors.
> replace recommonmark with myst-parser

- docs/getting-started/getting-started-with-cwl.rst
Clarified the note which discusses that Dockstore does not support CWL sbg:draft-2.
https://ucsc-cgl.atlassian.net/browse/DOCK-1940
> clarify CWL version support and ramifications

- requirements.txt
The last commit pinned the following versions to requirements.txt
> sphinx==4.4.0
> myst-parser==0.16.1
> sphinx_rtd_theme==0.4.3
> git+https://github.com/pdavide/sphinxcontrib-discourse
This combination results in bullet points disappearing, see [#4724](https://github.com/dockstore/dockstore/issues/4724). Updating to sphinx_rtd_theme 1.0.0 brings them back. 
I decided not to update myst-parser as the current version (0.17.something) breaks the inline URLs on docker_instructions.md; they still work as expected on 0.16.1
> Fix bullet points on develop

- docs/index.rst
- docs/news.rst
https://github.com/dockstore/dockstore/issues/4747
* Moves "news and events" to the "about" section on the sidebar and front page TOC
* TOC for news items is now generated by "news and events" RST, will only show in sidebar as dropdown when "news and events" is selected
* "News and events" page isn't blank
> Fix news section

- docs/faq.rst
- docs/getting-started/getting-started-with-galaxy.rst
- requirements.txt
I was trying to figure out what information does and does not belong on our FAQ page and realized I was struggling to keep track of the FAQ page as it currently exists. So, I made a version that divides it into sections. There are other changes I'm playing around with, but I want to propose this one first. I made sure to keep questions that have an `.._internal-identifier`, such as the one on verified workflows, together with that identifier, and added identifiers for the sections to create a bogus TOC (bogus in that it won't get double-indexed on the sidebar).
Would like some feedback for categories. I don't like the current miscellaneous one that I have, feels kind of like a cop out. Would also like feedback r/e having all questions on the top of the page instead of just the categories, …
> Reorganize FAQ page

- docs/_static/checksum-support.html
- docs/advanced-topics/checksum-support.rst
For https://github.com/dockstore/dockstore/issues/4345
Updated docs to add that Amazon ECR checksum harvesting is supported for tools and workflows. Also added a row for GitHub App tools which behaves like workflows for Docker image checksum harvesting
Is develop the correct branch for 1.12 work?
> Add Amazon ECR to Docker image checksum documentation

- docs/conf.py
These URLs appear to redirect to a different URL, but linkcheck should be able to handle that. No idea why that's happening but this workaround handles it. I don't like it, but there is already a doi.org URL getting skipped, so maybe this sort of thing has happened before?
> Skip all doi.org URLs in linkcheck

- docs/getting-started/dockstore-tools.rst
New PR replacing #187 
- I removed a lot of information to try to simplify the getting started. If a user is publishing a tool for the first time, I don't think they need to revisit our discussion of why we changed the tool definition.
- I removed the section about searching for other tools after registering your own tool. We should separate these user personas (tool developer vs. someone searching for a tool to reuse "end user").
> New PR on hotfix branch: Simplify registering tools

- docs/getting-started/dockstore-tools.rst
Feeling compassionate on my birthday so I will not make all of my hotfixes into one mega PR this time.
This one just removes some redundancies. dockstore-tools.rst does not need note--registration.rst twice, and note--legacy-dont-sync.rst already states that legacy methods are not recommended so we needn't say it immediately prior.
> Remove redundancies

- docs/index.rst
Likely a merge conflict that slipped under the radar... thanks to TLP for noticing this yesterday at storytime!
> System status now only in sidebar once

- docs/assets/templates/template.rst
- requirements.txt
Neither this version nor the old one mention Docker tags at all, but I think users new to Docker and git have a chance of getting the two mixed up. I swapped the order of the words and added "GitHub" right before "tags" in attempt to make it clearer, as well as linked GitHub's own docs on the two. Also included a sentence reminding users that they need to have their workflow/tool/service on Dockstore, just in case a user goes straight here without reading any of our other docs.
> Pin a dependency and clarify .dockstore.yml `filter` is not about Docker tags

- docs/advanced-topics/docker-alternatives.rst
We have a link to Docker's blog r/e rootless Docker. Recently, it has begun occasionally but not always failing during `make linkcheck`. As of my making this PR, builds are passing on CircleCI but my browser is still throwing gateway errors on that URL.
It just so happens the author of the blog mirrored it on Medium, so this is an easy fix. Will add reviewers + look to merge this if CI begins failing again. Might just be a temporary hiccup.
> Replace wonky link in docker-alternatives.rst

- README.md
- style-guide.md
This PR adds a style guide for our documentation. It loosely based on Google's style guide and repeats a few important points from it, but the emphasis is on parts specific to our users. It is written in markdown with the RST portions escaped as necessary to make it render as expected.
This PR does not attempt to change existing documentation to align with the guide, but once this is approved, I intend on making some changes to that end.
> Establish a style guide

- docs/conf.py
- docs/faq.rst
dockstore/dockstore#4243
This is such an out-there edge case, I'm not convinced we should have it, but I suppose it doesn't hurt. Screenshot from local build:
I went "use the Help Desk link" instead of an actual link in case we ever want to change the Help Desk url.
> Add a FAQ entry for duplicate ORCID accounts

- docs/index.rst
I got lost on a documentation website whose index I rewrote. I have only my hubris to blame. Now, it's time to make things right.
> Move dockstore.yml templates up in our sidebar

- style-guide.md
I think GitHub made a small change to how markdown is rendered, which broke one of our examples.
> Small formatting fix to style guide

- docs/advanced-topics/dockstore-cli/advanced-features.rst
https://ucsc-cgl.atlassian.net/browse/SEAB-4980
Adds a new row indicating that 1.14 uses cromwell version 84
> Add cromwell version 84 to table for 1.14

- docs/assets/templates/template.rst
- docs/assets/templates/workflows/example-3-multiworkflow-multiauthor.dockstore.yml
- docs/assets/templates/workflows/template-big.dockstore.yml
- docs/assets/templates/workflows/template-small.dockstore.yml
- docs/assets/templates/workflows/workflows.rst
- docs/dictionary.rst
- docs/getting-started/github-apps/github-apps.rst
* Adds readMePath to the big and small blank templates
* Adds readMePath to the multi-workflow template
* Add a tip that if you are making many entries from a single GitHub repo, each one needs a unique name* and should have a unique readme
* Add a selling point to the "Why use the GHA?" docs
_*iirc you can technically leave one workflow nameless provided n-1 have a name but that's not a good idea so I'm not going to remind users of that_
> Add information on readMePath

- docs/advanced-topics/wes/cli-wes-tutorial.rst
- docs/advanced-topics/wes/wes-cwl-agc-tutorial.rst
- docs/advanced-topics/wes/wes-wdl-agc-tutorial.rst
- docs/dictionary.rst
This PR adds a tutorial that a user can follow to launch a CWL workflow on Toil via the Amazon Genomics CLI.
This tutorial is very similar to the found [here](https://github.com/dockstore/dockstore-documentation/blob/bff75f1352bdd9f3c1cf1e60bbd22acf4630ee14/docs/advanced-topics/wes/wes-wdl-agc-tutorial.rst), just modified with slightly different commands and a different workflow.
**Review Instructions**
Follow the steps in the tutorial and confirm that
1. They work
2. They are easy to follow
**Issue**
https://github.com/dockstore/dockstore/issues/5435
[DOCK-2356](https://ucsc-cgl.atlassian.net/browse/DOCK-2356)
[DOCK-2356]: https://ucsc-cgl.atlassian.net/browse/DOCK-2356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Create Tutorial for Running CWL workflows on Toil via AGC

- docs/advanced-topics/wes/cli-wes-tutorial.rst
- docs/advanced-topics/wes/wes-cwl-agc-tutorial.rst
- docs/advanced-topics/wes/wes-wdl-agc-tutorial.rst
When working on #238, I noticed Flynn's AGC/WES doc was on develop only; there is no reason for it not to be on the release branch.
His doc was already been reviewed in a PR to develop, so a cursory review is probably fine.
> Merge AGC/WES doc from develop

- discourse-topic-check.sh
- docs/_static/language-support.html
- docs/advanced-topics/dockstore-tools-overhaul.rst
- docs/end-user-topics/language-support.rst
- docs/faq.rst
dockstore/dockstore#5402
While writing it, noticed that the notifications link in the language support table did not work; fixed that as well.
Build is [here](https://docs.dockstore.org/en/feature-5402-opendata/) if you wish to view the built form.
Discourse topic check was failing because a file existed on develop that didn't exist on the release1.14 branch. Updated to handle that case after discussion with Steve.
> Describe Open Data

- docs/advanced-topics/docker-alternatives.rst
- docs/advanced-topics/wes/wes-wdl-agc-tutorial.rst
Adds a note about how S3 urls are required to reference files from a WDL test parameter file on AWS AGC. 
Also, a podman page moved, this PR updates the link.
**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2347
[#5416](https://github.com/dockstore/dockstore/issues/5416)
> DOCK-2347: Mention AGC wdl input S3 URL requirement

- .github/PULL_REQUEST_TEMPLATE.md
- docs/advanced-topics/dockstore-cli/overview.rst
- docs/getting-started/getting-started-with-wdl.rst
- docs/getting-started/releasing-on-github.rst
- docs/index.rst
Gives a high-level overview of the CLI.
Given the potentially uncertain future of the CLI, I didn't want to delve into all the details of what it can do, and showed how the user can discover its features.
dockstore/dockstore#4835
DOCK-2127
> Create overview page for the CLI

- docs/conf.py
Right now, the following copyright notice appears at the end of each of our documentation pages:
```
© Copyright 2021, OICR, and UCSC.
```
2021 was years ago, so the above notice could make the pages feel stale.
This PR replaces converts the year to a range, starting in 2021 and ending at the current year:
```
© Copyright 2021-2024, OICR, and UCSC.
```
Ah, so much fresher!
The use of a range seems common, and as I understand it, the requirement is that the first year of publication should appear in the copyright notice (in this case, as the first year of the range).  Disclaimer: I am not a lawyer, and this is not legal advice.
Charles found this list of big org copyright notices:
https://www.termsfeed.com/blog/sample-copyright-notices/
I'd argue for removing the …
> Update copyright notice to include range ending in current year

- .circleci/config.yml
New discourse topics are only added to documentation pages after approval, which can cause build failures. 
By splitting the discourse topic check into a separate build job, each change to the documentation will trigger two CircleCI checks: "test" covers the build up to and excluding the discourse topic, while "topic" checks the entire build including the discourse topic. 
The goal is that, when adding to the documentation, it should be easier to identify whether or not the rest of the build succeeded (i.e. at least 1/2 checks passed).
**Issue**
[SEAB-6142](https://ucsc-cgl.atlassian.net/browse/SEAB-6142?atlOrigin=eyJpIjoiMzc1NWQ3NDljYWNlNDNiMWE2MDQxNjYzYTQ5YzJlMTQiLCJwIjoiaiJ9) …
> SEAB-6142: Split Up Documentation Build

- .circleci/config.yml
See [SEAB-6142: Split Up Documentation Build](https://github.com/dockstore/dockstore-documentation/commit/4a8ef4299776292345be675cab9313de05b85806#) for the original merge. The Python version for the `topic` job was not properly updated to 3.9 as per a [previous commit](https://github.com/dockstore/dockstore-documentation/commit/96e946c8a6f96a839e5470d025ca7ca45b616cf6), which caused a check to fail.
Updating all Python versions to 3.9 should fix the inconsistency and pass the checks.
**Issue**
[Ticket (SEAB-6142)](https://ucsc-cgl.atlassian.net/browse/SEAB-6142?atlOrigin=eyJpIjoiYmZmNTQwMWYxZTlkNDRlY2E2M2MwN2M3ZGIzYzJlYjkiLCJwIjoiaiJ9)
[Original PR](https://github.com/dockstore/dockstore-documentation/pull/258)
Please make sure that you've checked the following before …
> Update Python version to 3.9 for all jobs

- docs/_attic/glossary_entries.py
- docs/_attic/glossary_entries_list_dynamic.txt
- docs/advanced-topics/metrics.rst
- docs/assets/templates/notebooks/notebooks.rst
- docs/getting-started/getting-started-with-notebooks.rst
- docs/getting-started/github-apps/snippet--installation.rst
- docs/index.rst
- no-discourse-topic-required.txt
This PR makes some initial, basic, relatively non-controversial changes to the docs for the 1.15 notebook release:
1. Adds a "notebook" entry to the Dockstore dictionary.
2. Removes references to the notebooks feature flag and preview. 
3. Modifies some adjacent text to tighten and add "notebook" to the list of entry types.
More substantial changes are forthcoming in subsequent PRs.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5124 (best match)
> SEAB-5124: Adjust notebooks documentation

- docs/advanced-topics/best-practices/best-practices-development.rst
- docs/index.rst
The issue title is "Document CI/CD best practices for workflows"; I broadened it to general software engineering practices.
It's hard to strike the right balance; I can't replace a book. I was also running a bit out of steam. Hopefully this works, although it might be a little thin.
I don't really talk about CI/CD; I feel they're technically not the same thing as automated builds, although automated builds are part of CI. But I'm open to suggestions.
**Issue**
dockstore/dockstore#3669
> Describe Engineering Best Practices

- docs/faq.rst
This PR adds a line in the Open Data section of the FAQ that mentions that while our facet is open and free, accessing "non open data" may be requester's pay. 
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3518
> SEAB-3518: added line regarding requester pays in the FAQ

- .circleci/config.yml
Updates to the documentation repository tend to occur in clusters near release dates. As such, if a build fails due to a broken link, it can be unclear whether it was the most recent PR or an earlier event that produced the failed check.
Having a scheduled workflow that performs weekly checks should make it easier to trace the causes of link errors. It could also encourage us to monitor documentation links more regularly.
**Issue**
[SEAB-6149](https://ucsc-cgl.atlassian.net/browse/SEAB-6149?atlOrigin=eyJpIjoiMTM3MDk1MTJiZmZjNDZjY2JiOGIwZTZiNzRjNGEyZjgiLCJwIjoiaiJ9)
[SEAB-6149]: https://ucsc-cgl.atlassian.net/browse/SEAB-6149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
> SEAB-6149: Add workflow for weekly link check

- docs/getting-started/archive-on-dockstore.rst
- docs/getting-started/delete-on-dockstore.rst
I just checked the documentation page for the Delete entry and Archive entry features I created and some images seem to be too small. This PR fixes that.
Before fix:
Delete entry page
Archive entry page
After fix:
Delete entry page:
Archive entry page:
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6057
https://ucsc-cgl.atlassian.net/browse/SEAB-5979
> SEAB-5979 & SEAB-6057: fixed sizing on long images

- requirements.txt
This PR changes the version of some required Python packages as suggested by the following group of dependabot PRs:
https://github.com/dockstore/dockstore-documentation/pull/277
https://github.com/dockstore/dockstore-documentation/pull/279
https://github.com/dockstore/dockstore-documentation/pull/276
https://github.com/dockstore/dockstore-documentation/pull/278
Version 2.32.0 of `requests` was yanked due to some CVEs, so it was updated to the latest.
**Issue**
none
> Bump some requirements as suggested by dependabot PRs

- docs/_static/language-support.html
Noticed when reviewing another ticket, language support table says "Galaxy Galaxy..."
Before:
After:
**Issue**
Didn't create one.
> Add missing break

- docs/conf.py
RTD is deprecating an existing method of injecting the basename into your docs for if you use a custom domain. They suggest this change to make your docs work with the new method.
https://about.readthedocs.com/blog/2024/07/addons-by-default/
This PR is for the hotfix, there is another for develop https://github.com/dockstore/dockstore-documentation/pull/289
https://readthedocs.org/projects/dockstore/builds/25326501/
https://dockstore--290.org.readthedocs.build/en/290/
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6573
> Add baseurl from environment (hotfix)

- docs/conf.py
RTD is deprecating the old way of getting the baseurl. This is the change they require to support running RTD on a custom domain. Now uses RTD addons
https://about.readthedocs.com/blog/2024/07/addons-by-default/
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6573
> Add baseurl from environment

- docs/end-user-topics/dois.rst
This PR enhances the new "Automatic Dockstore DOI Generation" section.  It is an attempt to codify the bits of information present in this Slack thread: https://ucsc-gi.slack.com/archives/C05EZH3RVNY/p1730923309122769
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6738
> SEAB-6738: Tweak Automatic DOI Section

- docs/assets/templates/notebooks/template-big.dockstore.yml
- docs/assets/templates/notebooks/template-small.dockstore.yml
- docs/assets/templates/services/template-big.dockstore.yml
- docs/assets/templates/services/template-small.dockstore.yml
- docs/assets/templates/workflows/template-big.dockstore.yml
- docs/assets/templates/workflows/template-small.dockstore.yml
- docs/end-user-topics/dois.rst
Document DOI opt-out option in templates and in the DOI article. 
View draft at https://docs.dockstore.org/en/feature-document_enable_auto_doi/
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6833
> document auto dois opt-out setting
