docs/getting-started/getting-started-with-cwl.rst, docs/getting-started/getting-started-with-nextflow.rst, docs/getting-started/getting-started-with-wdl.rst
https://github.com/dockstore/dockstore/issues/2855
=> link user to onboarding from the getting started with CWL page

docs/_static/language-support.html, docs/advanced-topics/posting-zips.rst, docs/advanced-topics/set-up-file-provisioning-plugins.rst, docs/dockstore-introduction.rst, docs/end-user-topics/dnastack-launch-with.rst, docs/end-user-topics/end-user-topics.rst, docs/getting-started/getting-started-with-cwl.rst, docs/getting-started/getting-started-with-wdl.rst
Quick review of the current state of the docs
* superficial changes to version numbers
* formatting issues
* broken links
=> Overall review

docs/index.rst, docs/news.rst, docs/news/2019-09-26-Dockstore-1.7.0.rst
some comments while reviewing https://github.com/dockstore/dockstore/issues/2826
take a look at https://beta.docs.dockstore.org/en/review_changelog/
=> Review changelog

docs/advanced-topics/checker-workflows.rst
Minor change to checker workflow.  All files were already pointing to the master branch, not much change needed.
=> Checker workflow

docs/getting-started/getting-started-with-cwl.rst
https://github.com/dockstore/dockstore/issues/2943
add indents
=> bug/typo fix on CWL1.1 code snippet

docs/conf.py
Update release version
https://github.com/dockstore/dockstore/issues/3128
Version is being included in the docs title. Set to null so that docs are not versioned.
=> change version to empty

docs/getting-started/getting-started-with-cwl.rst, docs/news/2020-01-27-Dockstore-1.8.0.rst
Adds 1.8.0 release notes to the docs.
=> add 1.8.0 release notes

docs/advanced-topics/docker-alternatives.rst
=> updated install instructions and cromwell option

docs/_static/checksum-support.html, docs/advanced-topics/checksum-support.rst, docs/index.rst
https://ucsc-cgl.atlassian.net/browse/SEAB-1053
Viewable here https://docs.dockstore.org/en/feature-seab-2103-checksums/advanced-topics/checksum-support.html
=> checksum support

docs/dockstore-introduction.rst, docs/getting-started/getting-started-with-docker.rst, docs/getting-started/releasing-on-github.rst
For most of dockstore/dockstore#3134 
Seems like the Workflow section changes were already made beforehand.
Missing UI2 changes necessary for the issue.  Going to have another PR for it.
=> Tutorial Changes

docs/advanced-topics/advanced-features.rst
Addresses https://ucsc-cgl.atlassian.net/browse/SEAB-1081
=> Update WES documentation and fix plugin table

docs/advanced-topics/checksum-support.rst
https://docs.dockstore.org/en/feature-nextflowchecksumsupport/advanced-topics/checksum-support.html
=> nextflow checksum support

docs/advanced-topics/advanced-features.rst
Addresses https://ucsc-cgl.atlassian.net/browse/DOCK-1337
dockstore/dockstore#3431
=> remove spaces from text in table

docs/advanced-topics/posting-zips.rst
=> Make a note of deprecated endpoint

docs/advanced-topics/advanced-features.rst
Addresses:
dockstore/dockstore#3204
https://ucsc-cgl.atlassian.net/browse/DOCK-1198
=> Add table for Cromwell version used

docs/_static/language-support.html
dockstore/dockstore#3546
link working now https://docs.dockstore.org/en/3546-brokenlink/end-user-topics/language-support.html
=> fix broken link

docs/news/2020-07-06-Dockstore-1.9.0.rst
https://ucsc-cgl.atlassian.net/browse/SEAB-1489
Viewable here: https://docs.dockstore.org/en/feature-1.9.0-news/news/2020-07-06-Dockstore-1.9.0.html
=> 1.9.0 news

docs/getting-started/dockstore-tools.rst, docs/getting-started/getting-started-with-cwl.rst, docs/getting-started/getting-started-with-wdl.rst
Greg found some confusing parts of the docs, I've updated them.
https://github.com/dockstore/dockstore/issues/3583
Note I did not update the requirements.txt portion, since there is another ticket linked to the original one that looks into that.
=> added more explanations for confusing parts of the docs

docs/advanced-topics/organizations-and-collections.rst
=> update organization roles

docs/getting-started/github-apps/github-apps.rst
Part 1 of https://github.com/dockstore/dockstore/issues/3790 , Add simple warning when setting the descriptor language
=> Warning when setting descriptor language

docs/advanced-topics/organizations-and-collections.rst
=> update organization roles (#78)

docs/getting-started/github-apps/github-apps.rst
Ticket: https://ucsc-cgl.atlassian.net/browse/SEAB-1802
Differed from the examples and was not clear on which file to use for Nextflow descriptor.
=> Clarify Nextflow Descriptor for GitHub Apps

docs/assets/templates/.dockstore.yml, docs/getting-started/github-apps/github-apps.rst
Main issue: https://github.com/dockstore/dockstore/issues/3886
=> add .dockstore.yml filters documentation

docs/advanced-topics/best-practices/best-practices-secure-fair-workflows.rst, docs/index.rst
New best practices doc that has been reviewed already in Google Drive. Seeking reviews on:
- RST format
- anything missed before
=> added Best Practices for Secure and FAIR workflows

docs/faq.rst
Addresses dockstore/dockstore#4018
=> explain what renaming a repository does

docs/advanced-topics/best-practices/best-practices-secure-fair-workflows.rst
NHLBI reviewed Best Practices for secure and fair workflows doc and requested a few grammar updates.
=> Fixed issues NHLBI found

docs/advanced-topics/best-practices/best-practices-secure-fair-workflows.rst
- fixed grammar mistakes (missing periods)
- no remote imports (check my language here)
- no scripts as inputs
- DockerHub updates
=> additions to best practices

docs/conf.py, docs/end-user-topics/ORCID.rst
For https://ucsc-cgl.atlassian.net/browse/SEAB-2946 
Mention export to ORCID
=> Mention export to ORCID

docs/assets/templates/.dockstore.yml, docs/getting-started/github-apps/github-apps.rst
Documentation for specifying authors with .dockstore.yml
=> multiple authors .dockstore.yml documentation

docs/getting-started/github-apps/github-apps.rst
Adds a note about the new .dockstore.yml tag
=> Add default latest version tag info

docs/getting-started/getting-started-with-cwl.rst
=> sbg support

docs/faq.rst
https://ucsc-cgl.atlassian.net/browse/SEAB-3146
Missed this one when making other changes
=> Update documentation for discuss contact

docs/getting-started/github-apps/github-apps.rst
For dockstore/dockstore#4179
Add a TL;DR in hopes that it will be read
=> Update GitHub Apps documentation

README.md, docs/getting-started/github-apps/migrating-workflows-to-github-apps.rst
As mentioned on Slack, I am not convinced that this conversion process works as described. However, there is one thing that we know for sure, and that's that the UI has since been updated. Might as well make those changes now.
=> Small update to migrating-workflows-to-github-apps.rst

docs/conf.py, docs/getting-started/getting-started-with-galaxy.rst, docs/launch-with/galaxy-launch-with.rst
=> Avani's galaxy updates

docs/getting-started/github-apps/migrating-workflows-to-github-apps.rst
Cherry picked from quick-updates branch, same content as that one.
(In the future I'll try to come up with better branch names!)
=> Update github apps to show what is in our UI

docs/getting-started/dockstore-workflows.rst, docs/getting-started/intro-to-dockstore-tools-and-workflows.rst, docs/index.rst
dockstore/dockstore#4542
https://docs.dockstore.org/en/feature-4542-describetoolsbetter/getting-started/intro-to-dockstore-tools-and-workflows.html
=> Explain Dockstore Tools and Workflows better

docs/advanced-topics/tools-vs-workflows.rst, docs/getting-started/dockstore-tools.rst, docs/getting-started/dockstore-workflows.rst, docs/getting-started/github-apps/github-apps-troubleshooting-tips.rst, docs/getting-started/intro-to-dockstore-tools-and-workflows.rst, docs/index.rst
This is the same as #163 but it doesn't have the extra commits from develop added by mistake. I had previously based that branch on develop, then changed the branch I was merging into, so it was picking up a lot of stray commits.
=> Modify getting started tutorial -- now with the correct commits!

docs/advanced-topics/checksum-support.rst
=> Support for sha-256

docs/advanced-topics/checksum-support.rst, docs/conf.py
Addresses https://ucsc-cgl.atlassian.net/browse/DOCK-1861
=> spell out docker checksum version support

docs/advanced-topics/dockstore-cli/advanced-features.rst, docs/conf.py
Updates the CLI Cromwell support table
=> mention cromwell version used in cli 1.12

docs/getting-started/getting-started-with-services.rst, docs/getting-started/intro-to-dockstore-tools-and-workflows.rst
Prior PR #186 was accidentally based on the wrong branch
=> New PR with only my edits cherrypicked for updating intro page

docs/advanced-topics/docker-alternatives.rst, docs/news/2016-09-13-Genome-canada-grant.rst
Replacing the genomecanada link an archive.org link might not be the best look... thoughts?
=> Fix `make linkcheck` (affects #200 and #201)

docs/news/2016-09-13-Genome-canada-grant.rst
#202 was based on #200, so it can't be directly merged into hotfix without some wizardry. Seems easier to just copy the changes into a new branch and merge them again.
=> Actually fix linkcheck on hotfix branch

docs/advanced-topics/dockstore-cli/yaml-command-line-validator-tool.rst, docs/index.rst
This PR adds documentation for the Yaml Validator Tool in the CLI.
**ISSUE**
[SEAB-4503](https://ucsc-cgl.atlassian.net/browse/SEAB-4503)
=> Yaml Command Line Validator Tool Documentation

docs/_static/checksum-support.html
confirmed in https://github.com/dockstore/dockstore/issues/4842#issuecomment-1217190272
=> add ghcr to table

docs/advanced-topics/dockstore-cli/advanced-features.rst, docs/news/2019-04-08-Dockstore-1.6.0.rst
updated documentations to show correct versions of Cromwell
related ticket: https://ucsc-cgl.atlassian.net/browse/SEAB-4014
=> updated cromwell version and removed outdated info

docs/advanced-topics/docker-alternatives.rst
Updated documentations by removing outdated versions and added podman documentation
Related issue/ticket: https://ucsc-cgl.atlassian.net/browse/DOCK-2236
=> added podman documentation

docs/advanced-topics/verification.rst, docs/news/2016-07-09-ISMB-tutorial.rst
Side-effect of https://github.com/dockstore/dockstore-ui2/pull/1877
=> Remove gitter

.gitignore, docs/advanced-topics/metrics.rst, docs/faq.rst
This PR modifies the metrics documentation so that it describes the steps that a platform has to take to start submitting metrics to Dockstore. The existing sections are re-arranged a bit which makes it more obvious that the metrics documentation is platform-focused.
I recommend checking this out locally to see the formatting.
**Issue**
[SEAB-5941](https://ucsc-cgl.atlassian.net/browse/SEAB-5941)
[SEAB-5941]: https://ucsc-cgl.atlassian.net/browse/SEAB-5941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Document a metrics guide for platforms

docs/faq.rst
Looks like whitespace formatting is the issue. 
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6560
=> Fix whitespace
